name: "Build and push Docker image"

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
        registry: ${{secrets.DOCKER_REGISTRY}}
        username: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        password: ${{secrets.DOCKER_REGISTRY_USERNAME}}

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: test-app:v0.1.0