name: "Build and push Docker image"

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/maciej-zieniewicz/test-app:v0.1.2
